src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }

   
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Entity\Produit;
use App\Entity\Commande;
use App\Service\CartService;
use App\Repository\ProduitRepository;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Loader\Configurator\request;

class CartController extends AbstractController

{
    #[Route('/cart', name: 'app_cart')]
    public function index(CartService $cs): Response
    {
        $dataPanier = $cs->dataPanier();
        $total = $cs->total();              

        return $this->render('cart/index.html.twig', [
            'dataPanier' => $dataPanier,
            'total' => $total
        ]);
    }

    #[Route('/cart/add/{id}', name: 'cart_add')]
    public function add($id, CartService $cs) {
        $cs->add($id);
        
       
        return $this->redirectToRoute('app_cart');
    }

    #[Route('/cart/remove/{id}', name:'cart_remove')]
    public function remove($id, CartService $cs) {

        $cs->remove($id);
        

        return $this->redirectToRoute('app_cart');
    }

    #[Route('/cart/commandes', name: 'commandes')]
    public function commande(EntityManagerInterface $manager, ProduitRepository $repo, CartService $cs, RequestStack $rs): Response
    {
        $dataPanier = $cs->datapanier();
        $session = $rs->getSession();
    
        foreach ($dataPanier as $item) {
            $produit = $item['produit'];
            $quantite = $item['quantite'];
            $commande = new Commande;
            $commande->setProduit($produit)
                ->setMembre($this->getUser())
                ->setQuantite($quantite)
                ->setMontant($produit->getPrix() * $quantite)
                ->setEtat("En cours d'enregistrement")
                ->setDateEnregistrement(new \DateTime());
    
            $manager->persist($commande);
        }
    
        $manager->flush();


        $session->remove('panier');
        $cs->clearCart();    
        $session->set('qt', 0);    
        $this->addFlash("success", "La commande a été bien mise en compte");
        return $this->redirectToRoute('home');
    }
    
    
    
    #[Route('/cart/commandes/delete/{id}', name: 'commande_delete')]
    public function deleteCommande(EntityManagerInterface $manager, Commande $commande)
{
    $manager->remove($commande);
    $manager->flush();
    $this->addFlash("success", "La commande a été supprimée");
    return $this->redirectToRoute('commandes');
}

#[Route('/cart/commandes/show', name: 'cart_show')]
public function show(CommandeRepository $repo) {
    $commandes = $repo->findAll();

    return $this->render('cart/commandes.html.twig', [
        'commandes' => $commandes, 
    ]);
}
}

templates/cart/commandes.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion de commandes
{% endblock
%}
{% block body %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success text-center w-50 mx-auto my-2">
			{{ message }}
		</div>
	{% endfor %}
	<div class="container-fluid">
		<h1 class="text-center my-3">Gestion de commandes</h1>
		<table class="table table-light">
			<thead class="text-center">
				<td>Commande n°</td>
				<td>Membre</td>
				<td>Produit</td>
				<td>Quantité</td>
				<td>Total</td>
				<td>Etat</td>
				<td>Date et Heure d'Enregistrement</td>
				<td>Actions</td>
			</thead>
			<tbody class="text-center">
				{% for item in commandes %}
					<tr>
						<td>{{ item.id }}</td>
						<td>
							{{ item.membre.id }}
							-
							{{ item.membre.prenom }}
							-
							{{ item.membre.nom }}
							-
							{{ item.membre.email }}
						</td>
						<td>{{ item.produit.id }}
							-
							{{ item.produit.titre }}</td>
						<td>{{item.quantite}}</td>
						<td>{{item.produit.prix}}
							€</td>
						<td>{{ item.etat }}</td>
						<td>{{item.dateEnregistrement|date('d/m/Y à H:i:s')}}</td>
						<td class="col-2">
							<a href="#" class="text-info me-2">
								<i class="fa fa-search"></i>
							</a>
							<a href="" class="text-warning me-2">
								<i class="fa fa-edit"></i>
							</a>
							<a href="{{ path('commande_delete', { id: item.id }) }}" class="text-danger">
								<i class="fa fa-trash"></i>
							</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="text-center mt-3">Votre panier</h1>
		{% if dataPanier %}
			<div class="table-responsive">
				<table class="table table-primary text-center mt-3">
					<thead>
						<tr>
							<th></th>
							<th>Produit</th>
							<th>Quantité</th>
							<th>Prix</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						{% for item in dataPanier %}
							<tr>
								<td><img src="{{asset('uploads/images/' ~ item.produit.photo)}}" alt="{{ item.produit.titre }}" style="object-fit: cover" width="100" height="100"/></td>
								<td>{{item.produit.titre}}</td>
								<td>{{item.quantite}}</td>
								<td>{{item.produit.prix}}
									€</td>
								<td>
									<a href="{{path('cart_remove', {id: item.produit.id})}}" class="btn-sm btn-info p-1">X</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<h5 class="text-end text-primary me-4">Total:
					{{total}}
					€</h5>
				<div class="text-center">
					<a href="{{path('commandes')}}" class="btn btn-primary">Valider mon panier</a>
				</div>

			</div>
		</div>
	</div>
{% else %}
	<h2 class="text-center my-3 ">Votre panier est vide</h2>
{% endif %}{% endblock %}